### ISSUE TITLE
SIFT feature matches files format

### ISSUE THREAD

**Issue by yzhang93** [hlzz/DeepMatchVO#1]
Hi, Thanks for sharing the codes! 

I have a question regarding feature matches _cam.txt file. There are 200 (2*100) lines of matching coordinates for two image pairs. And I assume the first 100 is target image (time t) with source image (time t-1) and the last 100 is target image with source image (time t+1). Do I interpret this correctly?

And for each line, it should be two points (x1, y1, x2, y2). Is p1 (x1, y1) always from target image, and p2 from source image (t-1 or t+1)?

**Comment by hlzz** [comment]
Hi @yzhang93 , thanks for your interests! You are absolutely right, the first 100 lines are matches between t and (t-1), the last 100 are that between t and (t+1). And yes, (x1, y1) is always from the target image. Feel free to post more questions if you have.

**Comment by yzhang93** [comment]
Hi @hlzz,

Thanks for your quick reply! I was trying to replicate your experiments and results using your pre-computed match files. I got the same evaluation results using your pre-trained model. 

But when I trained a model from scratch using the provided training command and the default parameters, the pose estimation results were much worse than in your paper.

For snippet results, I've got 0.0106 (seq 09) and 0.0092 (seq 10) which are close. But for full trajectory ATE (evaluated using evo), I've got 60.77 (seq 09) and 40.28 (seq 10). Is there any special tunes or different parameters used to have the best model? Did you use any pre-trained weights from Resnet-50?

```
#Training command I was using
match_num=100
python train.py --dataset_dir=$kitti_odom_match3 --checkpoint_dir=$checkpoint_dir --img_width=416 --img_height=128 --batch_size=4 --seq_length 3 \
    --max_steps 300000 --save_freq 2000 --learning_rate 0.001 --num_scales 1  --match_num $match_num
```

**Comment by hlzz** [comment]
@yzhang93 Great! Did you use the provided `generate_full_pose.py` script for the full sequence evaluation? In my experience, the ATE results for full trajectory is indeed unstable given different models. But 60.77 and 40.28 (for seq9/10) still seem a bit too large for me. I suggest you try different models around the best one you have, and see how much they fluctuate. Also, the full sequence performance is just a weak indicator for how good the relative pose is, because we didn't take serious consideration for the scale alignment. We only consider the motion average between adjacent frames in `generate_full_pose.py`, not the full pose.

**Comment by yzhang93** [comment]
@hizz Thanks for your advice. I did see much fluctuation in different models. Now I get results much closer to your results. Thanks again for your help.

**Comment by hlzz** [comment]
@yzhang93 Sounds great! Did you start from scratch or using some pre-trained models?
